<?php

namespace App\Service;

use App\SocialFacebookAccount;
use App\User;
use Laravel\Socialite\Contracts\User as ProviderUser;

class SocialFacebookAccountService
{
    public function createOrGetUser(ProviderUser $providerUser)
    {
        $account = SocialFacebookAccount::whereProvider('facebook')
            ->whereProviderUserId($providerUser->getId())
            ->first();
        if ($account) {
            return $account->user;
        } else {
            $account = new SocialFacebookAccount([
                'provider_user_id' => $providerUser->getId(),
                'provider' => 'facebook'
            ]);
            $user = User::whereEmail($providerUser->getEmail())->first();
            if (!$user) {
                $user = User::create([
                    'email' => $providerUser->getEmail(),
                    'first_name' => ucwords(strtolower($providerUser->user['first_name'])),
                    'last_name' => ucwords(strtolower($providerUser->user['last_name'])),
                    'password' => md5(rand(1, 10000)),
                    'password_autogenerated' => true
                ]);
            }
            $account->user()->associate($user);
            $account->save();
            return $user;
        }
    }
}
